#!/bin/bash

# Script para corregir permisos específicos de los directorios de upload
# Ejecuta comandos directos en el servidor

echo "🔧 Comandos para corregir permisos de directorios de upload"
echo ""
echo "Ejecuta estos comandos EN EL SERVIDOR (como root):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /home/api.heroedelwhisky.com.ar/public_html/apps/backend"
echo ""
echo "# Verificar usuario de PHP-FPM workers"
echo "ps aux | grep 'php-fpm: pool' | grep -v grep | head -1"
echo ""
echo "# Verificar permisos actuales"
echo "ls -ld storage/app/public/system/logos"
echo "ls -ld storage/app/public/system/favicons"
echo ""
echo "# Configurar permisos con setgid para que los nuevos archivos hereden el grupo"
echo "chmod 2775 storage/app/public/system"
echo "chmod 2775 storage/app/public/system/logos"
echo "chmod 2775 storage/app/public/system/favicons"
echo ""
echo "# Configurar ownership (ajusta USER según el resultado del primer comando)"
echo "chown -R www-data:www-data storage/app/public/system"
echo ""
echo "# O si el usuario PHP-FPM es diferente (por ejemplo nginx):"
echo "# chown -R nginx:nginx storage/app/public/system"
echo ""
echo "# Verificar permisos finales"
echo "ls -ld storage/app/public/system"
echo "ls -ld storage/app/public/system/logos"
echo "ls -ld storage/app/public/system/favicons"
echo ""
echo "# Probar escritura como el usuario PHP-FPM"
echo "# Si PHP-FPM es www-data:"
echo "sudo -u www-data touch storage/app/public/system/logos/test.txt && sudo -u www-data rm storage/app/public/system/logos/test.txt && echo '✅ Escritura OK' || echo '❌ Error de escritura'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 SOLUCIÓN RÁPIDA (copia y pega todo en el servidor):"
echo ""
echo "cd /home/api.heroedelwhisky.com.ar/public_html/apps/backend && chmod -R 2775 storage/app/public/system && chown -R www-data:www-data storage/app/public/system && sudo -u www-data touch storage/app/public/system/logos/test.txt && sudo -u www-data rm storage/app/public/system/logos/test.txt && echo '✅ Permisos correctos' || echo '❌ Revisa el usuario PHP-FPM'"
echo ""

